'''
Created on Feb 24, 2017

@author: Robert
'''

### SCREEN ###
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600

### ACTORS ###
SIMPLE_BOX_WIDTH = 60
SIMPLE_BOX_HEIGHT = 60

### COLORS ###
COLOR_BLACK = (0, 0, 0)
COLOR_BLUE = (0, 128, 255)
COLOR_ORANGE = (255, 100, 0)

### SOUNDEFFECTS ###
SOUND_COLORSWAP = 'click'

### SOUNDTRACK ###
SONG_SAGAWATER = 'saga7-Water'

### AMBIANT TRACKS ###
AMB_CITY = 'city'