'''
Created on Feb 25, 2017

@author: Robert
'''

import parameters as PRAM

'''
Class to contain data and actions for a PC.  Actions are added to the object
    and modified dynamically
@param actor
'''
class PlayerCharacter():
    def __init__(self, actor=None):
        self.actor = actor #link to the actor player is controlling
                
        #explicitly declare fields
        self.moveSpeed = 7
        self.moveListeners = [] #to check for events generated by touch
        
    def addListener(self, listenerType, listener):
        if listenerType == PRAM.LISTENER_MOVE:
            self.moveListeners.append(listener)
